### ISSUE TITLE
In harness section, for arbitary input formats harness, how to write a file input test harness

### ISSUE THREAD

**Issue by NanFeng009** [mykter/afl-training#19]
If write harness as example https://github.com/mykter/afl-training/tree/main/harness#arbitrary-input-formats 
 the harness can tell which case to run based on the 1st parameter.
In this circumstances, how to make the harness read from input file? if we write the "echo" and "mul" in seed file, the AFL will mutate the "echo" and "mul" as well. if we just write the parameters in seed file, how the harness know whether lib_echo or mul be called?

**Comment by mykter** [comment]
> if we write the "echo" and "mul" in seed file, the AFL will mutate the "echo" and "mul" as well. 

That's right, so there are two ways you could go:
 1. Decide which function to fuzz based on the commandline, like in the example. The only change is where the data is coming from - a file rather than stdin.
 2. Treat, say, the first byte of the file as an indicator as to what function to fuzz. e.g. if the first byte ==0, invoke mul, otherwise invoke echo. This feels a bit strange at first, but will work perfectly well.
